version: "2.3"

services:


  gateway:
    container_name: gateway
    build: ./gateway
    network_mode: host
    command: nodemon server.js
    environment:
      - RABBIT_MQ_HOST=localhost:5673
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=epharmacy
      - CURRENT_DOMAIN=http://52.221.46.156:4500/static
    volumes:
      - ./gateway:/node/epharmacy/app
      - ./common:/node/epharmacy/common
    ports:
      - "4500:3500"
    restart: always

  user:
    container_name: user
    build: ./user
    command: nodemon server.js
    network_mode: host
    environment:
      - RABBIT_MQ_HOST=localhost:5673
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=epharmacy
      - RABBIT_MQ_PATTERN=user.*
      - CURRENT_DOMAIN=http://52.221.46.156:4500/static
    volumes:
      - ./user:/node/epharmacy/app
      - ./common:/node/epharmacy/common
    restart: always


  inventory:
    container_name: inventory
    build: ./inventory
    command: nodemon server.js
    network_mode: host
    environment:
      - RABBIT_MQ_HOST=localhost:5673
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=epharmacy
      - RABBIT_MQ_PATTERN=inventory.*
      - CURRENT_DOMAIN=http://52.221.46.156:4500/static
    volumes:
      - ./inventory:/node/epharmacy/app
      - ./common:/node/epharmacy/common
    restart: always

networks:
  default:
    external:
      name: epharmacy

