version: "3.3"

services:

  gateway:
    container_name: gateway
    build: ./gateway
    command: nodemon app.js --legacy-watch
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=framework
      - RABBIT_MQ_PATTERN=gateway.*
      - RABBIT_MQ_QUEUE_NAME=gateway
      - RABBIT_MQ_EXCHANGE_NAME=framework
      - MONGODB_DBNAME=user
      - MONGODB_HOST=mongodb
      - CURRENT_DOMAIN=http://localhost:8080/api/static
      - JWT_SECRET=epharmacy
      - PORT=80
    #      - DEBUG=*
    ports:
      - "4500:80"
    volumes:
      - ./gateway:/var/app/
      - ./common/utils:/var/app/modules/utils
      - ./common/models:/var/app/modules/models
    restart: always

  user:
    container_name: user
    build: ./user
    command: nodemon app.js --legacy-watch
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=framework
      - RABBIT_MQ_PATTERN=user.*
      - RABBIT_MQ_QUEUE_NAME=user
      - RABBIT_MQ_EXCHANGE_NAME=framework
      - MONGODB_DBNAME=user
      - CURRENT_DOMAIN=http://localhost:8080/api/static
      - MONGODB_HOST=mongodb
      - PORT=80
      - JWT_SECRET=epharmacy
    #      - DEBUG=*
    volumes:
      - ./user/:/var/app/
      - ./common/utils:/var/app/modules/utils
      - ./common/models:/var/app/modules/models
    restart: always


  inventory:
    container_name: inventory
    build: ./inventory
    command: nodemon app.js --legacy-watch
    environment:
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_USER=root
      - RABBIT_MQ_PASSWORD=framework
      - RABBIT_MQ_PATTERN=inventory.*
      - RABBIT_MQ_QUEUE_NAME=inventory
      - RABBIT_MQ_EXCHANGE_NAME=framework
      - MONGODB_DBNAME=inventory
      - MONGODB_HOST=mongodb
      - PORT=80
      - CURRENT_DOMAIN=http://localhost:8080/api/static

    #      - DEBUG=*
    volumes:
      - ./inventory:/var/app/
      - ./common/utils:/var/app/modules/utils
      - ./common/models:/var/app/modules/models
    restart: always
networks:
  default:
    external:
      name: epharmacy
